project:
  type: website
  output-dir: docs

website:
  title: "Mikko Impi√∂"
  navbar:
    right:
      - href: index.qmd
        text: About
      - blog.qmd
      - publications.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com

format:
  html:
    theme: [litera, custom.scss]
